#%RAML 1.0
title: "Take-home"
description: "A cool API built for Glia"
version: "1.0.0"
protocols:
- "HTTP"
mediaType:
- "text/plain"
securitySchemes:
  Basic auth:
    type: "base64 user:password"
securedBy:
- "Basic auth"
/words:
  displayName: "Scramble words"
  post:
    displayName: "Scramble a given word"
    body:
      type: "string"
      example:
        value: palabra
    responses:
      200:
        body:
          type: "string"
          example:
            value: aarbpal
            strict: false
      400:
        body:
          application/json:
            type: "error"
            example:
              value: "{\
              \n\"Error\": \"Invalid input - only letters are allowed!\",\
            \n}"
      403:
        body:
          application/json:
            type: "error"
            example:
              value: "{\
              \n\"Error\": \"Wrong or incomplete auth in request\",\
            \n}"
/audit:
  displayName: "Audit trail"
  get:
    displayName: "Get last 10 API calls"
    responses:
      200:
        body:
          application/json:
            type: "object"
            example:
              value: "{\
              \n\"API\": \"words\",\
              \n\"payload\": \"palabras\",\
            \n}"
            strict: false
      403:
        body:
          application/json:
            type: "error"
            example:
              value: "{\
              \n\"Error\": \"Wrong or incomplete auth in request\",\
            \n}"
